import { FormEvent, useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ColumnDef, flexRender, getCoreRowModel, useReactTable } from '@tanstack/react-table'
import { Archive, Bot, Check, ChevronRight, Database, FileSearch, FolderUp, GitCompareArrows, Home, LoaderCircle, Plus, RefreshCw, Search, Settings, ShieldCheck, SlidersHorizontal, X } from 'lucide-react'
import { Backup, bootstrap, CostItem, formatAmount, ImportIssue, ImportJob, Project, request, Rule, SearchResult } from './api'

type View = 'overview' | 'imports' | 'explorer' | 'matching' | 'rules' | 'settings'
const labels: Record<View, string> = { overview: '总览', imports: '项目与导入', explorer: '造价数据检索', matching: '清单匹配', rules: '标准化规则', settings: '备份与 AI' }
const nav = [['overview', Home], ['imports', FolderUp], ['explorer', FileSearch], ['matching', GitCompareArrows], ['rules', SlidersHorizontal], ['settings', Settings]] as const
const Button = ({ children, className = '', ...props }: React.ButtonHTMLAttributes<HTMLButtonElement>) => <button className={`button ${className}`} {...props}>{children}</button>
const Status = ({ value }: { value: string }) => <span className={`status status-${value}`}>{({ published: '已发布', review: '待复核', completed: '已完成', running: '解析中', queued: '等待中', draft: '草稿', resolved: '已处理', ignored: '已忽略', open: '待处理', complete: '成功' } as Record<string, string>)[value] || value}</span>
const Empty = ({ text }: { text: string }) => <div className="empty"><Database /><strong>{text}</strong><span>完成首次导入后，这里会显示可核查的数据。</span></div>
const ErrorLine = ({ error }: { error: unknown }) => error ? <div className="error-line">{error instanceof Error ? error.message : '请求失败'}</div> : null

export function App() {
  const [view, setView] = useState<View>('overview'); const health = useQuery({ queryKey: ['health'], queryFn: bootstrap })
  return <div className="shell"><aside><div className="brand"><span className="brand-mark">衡</span><div><strong>衡鉴造价库</strong><small>技术预览版 0.1</small></div></div><nav aria-label="主导航">{nav.map(([id, Icon]) => <button key={id} className={view === id ? 'active' : ''} onClick={() => setView(id)}><Icon />{labels[id]}</button>)}</nav><div className="local-state"><ShieldCheck /><div><strong>数据保存在本机</strong><small>{health.isSuccess ? '本地服务运行正常' : '正在连接本地服务'}</small></div></div></aside><main><header><div><span>个人造价数据库</span><ChevronRight /><strong>{labels[view]}</strong></div><span className="preview">人工样本技术预览</span></header>{view === 'overview' && <Overview go={setView} />}{view === 'imports' && <Imports />}{view === 'explorer' && <Explorer />}{view === 'matching' && <Matching />}{view === 'rules' && <Rules />}{view === 'settings' && <SystemSettings />}</main></div>
}

function Overview({ go }: { go: (v: View) => void }) {
  const stats = useQuery({ queryKey: ['dashboard'], queryFn: () => request<Record<string, number>>('/dashboard') }); const projects = useQuery({ queryKey: ['projects'], queryFn: () => request<Project[]>('/projects') }); const d = stats.data || { projects: 0, published_versions: 0, cost_items: 0, open_issues: 0 }
  return <section className="page"><Title title="数据工作总览" text="先处理异常，再使用已发布数据进行检索与比较。"><Button className="primary" onClick={() => go('imports')}><Plus />导入项目</Button></Title><ErrorLine error={stats.error} /><div className="stats"><div><span>项目</span><strong>{d.projects}</strong></div><div><span>已发布版本</span><strong>{d.published_versions}</strong></div><div><span>可检索清单项</span><strong>{d.cost_items}</strong></div><div className="warn"><span>待处理异常</span><strong>{d.open_issues}</strong></div></div><div className="panel"><div className="panel-head"><div><h2>最近项目</h2><p>发布后才进入正式检索库</p></div></div>{!projects.data?.length ? <Empty text="尚未导入项目" /> : <div className="table-scroll"><table><thead><tr><th>项目</th><th>地区 / 时间</th><th>专业</th><th>计价体系</th><th>清单项</th><th>版本</th></tr></thead><tbody>{projects.data.map(p => <tr key={p.id}><td><strong>{p.name}</strong><small>{p.result_stage}</small></td><td>{p.region}<small>{p.pricing_date}</small></td><td>{p.specialty}</td><td>{p.pricing_mode}</td><td>{p.item_count}</td><td><Status value={p.latest_status || 'draft'} /></td></tr>)}</tbody></table></div>}</div></section>
}

function Title({ title, text, children }: { title: string; text: string; children?: React.ReactNode }) { return <div className="page-title"><div><h1>{title}</h1><p>{text}</p></div>{children}</div> }

function Imports() {
  const qc = useQueryClient(), [open, setOpen] = useState(false), [selected, setSelected] = useState<string>(); const projects = useQuery({ queryKey: ['projects'], queryFn: () => request<Project[]>('/projects') }); const jobs = useQuery({ queryKey: ['imports'], queryFn: () => request<ImportJob[]>('/imports'), refetchInterval: q => q.state.data?.some(j => ['queued', 'running'].includes(j.status)) ? 1200 : false }); const issues = useQuery({ queryKey: ['issues', selected], queryFn: () => request<ImportIssue[]>(`/imports/${selected}/issues`), enabled: !!selected }); const resolve = useMutation({ mutationFn: ({ job, issue }: { job: string; issue: string }) => request(`/imports/${job}/issues/${issue}`, { method: 'PATCH', body: JSON.stringify({ status: 'ignored', resolution: '用户确认忽略' }) }), onSuccess: () => { qc.invalidateQueries({ queryKey: ['issues'] }); qc.invalidateQueries({ queryKey: ['imports'] }) } }); const publish = useMutation({ mutationFn: (id: string) => request(`/imports/${id}/publish`, { method: 'POST' }), onSuccess: () => { qc.invalidateQueries(); setSelected(undefined) } })
  return <section className="page"><Title title="项目与导入" text="原始文件按哈希归档，异常复核后事务发布。"><Button className="primary" onClick={() => setOpen(true)}><FolderUp />选择 Excel</Button></Title><ErrorLine error={jobs.error || publish.error} /><div className="split"><div className="panel"><div className="panel-head"><h2>导入任务</h2><Button title="刷新" onClick={() => jobs.refetch()}><RefreshCw /></Button></div>{!jobs.data?.length ? <Empty text="暂无导入任务" /> : <div className="task-list">{jobs.data.map(j => <button key={j.id} className={selected === j.id ? 'selected' : ''} onClick={() => setSelected(j.id)}><div><strong>{projects.data?.find(p => p.id === j.project_id)?.name || '项目'}</strong><small>{new Date(j.created_at).toLocaleString()} · {j.processed_files}/{j.total_files} 文件</small></div><div className="progress"><span style={{ width: `${j.progress}%` }} /></div><Status value={j.status} />{j.open_issue_count > 0 && <b>{j.open_issue_count}</b>}</button>)}</div>}</div><div className="panel review"><div className="panel-head"><div><h2>异常复核</h2><p>未识别内容不会静默进入正式数据</p></div>{selected && jobs.data?.find(j => j.id === selected)?.status === 'review' && <Button className="primary" onClick={() => publish.mutate(selected)}><Check />发布版本</Button>}</div>{!selected ? <Empty text="请选择导入任务" /> : !issues.data?.length ? <Empty text="该任务没有异常" /> : <div className="issue-list">{issues.data.map(i => <article key={i.id}><div><Status value={i.status} /><code>{i.code}</code></div><strong>{i.message}</strong><small>{i.sheet_name || '工作簿'} {i.cell_range || ''}</small>{i.status === 'open' && <Button onClick={() => resolve.mutate({ job: selected, issue: i.id })}><X />忽略并记录</Button>}</article>)}</div>}</div></div>{open && <ImportDialog close={() => setOpen(false)} done={() => { setOpen(false); qc.invalidateQueries() }} />}</section>
}
function ImportDialog({ close, done }: { close: () => void; done: () => void }) {
  const [files, setFiles] = useState<FileList | null>(null), [error, setError] = useState(''); const submit = async (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget), body = new FormData(); body.set('metadata_json', JSON.stringify({ name: f.get('name'), region: f.get('region'), pricing_date: f.get('pricing_date'), specialty: f.get('specialty'), pricing_mode: f.get('pricing_mode'), result_stage: f.get('result_stage'), area: f.get('area') || null })); if (files) Array.from(files).forEach(file => body.append('files', file)); try { await request('/imports', { method: 'POST', body }); done() } catch (x) { setError(x instanceof Error ? x.message : '导入失败') } }
  return <div className="modal-backdrop"><form className="modal" onSubmit={submit}><div className="panel-head"><h2>导入项目 Excel</h2><Button type="button" onClick={close}><X /></Button></div><div className="form-grid"><label className="span-2">项目名称<input name="name" required /></label><label>地区<input name="region" defaultValue="西安" required /></label><label>计价时间<input name="pricing_date" type="month" required /></label><label>专业<select name="specialty"><option>土建</option><option>安装</option><option>市政</option><option>装饰</option></select></label><label>计价体系<select name="pricing_mode"><option>内地清单定额</option><option>港式清单</option></select></label><label>成果阶段<select name="result_stage"><option>结算</option><option>预算</option><option>概算</option></select></label><label>建筑面积（m²）<input name="area" /></label><label className="span-2 file-drop">Excel 文件<input type="file" multiple accept=".xlsx,.xlsm" required onChange={e => setFiles(e.target.files)} /><span>支持清单计价、综合单价分析、工料机和措施项目表</span></label></div>{error && <div className="error-line">{error}</div>}<footer><Button type="button" onClick={close}>取消</Button><Button className="primary"><FolderUp />开始导入</Button></footer></form></div>
}

function Explorer() {
  const [query, setQuery] = useState(''), [unit, setUnit] = useState(''), [active, setActive] = useState(''), [selected, setSelected] = useState<string[]>([]); const result = useQuery({ queryKey: ['search', query, unit], queryFn: () => request<SearchResult>(`/cost-items/search?query=${encodeURIComponent(query)}&unit=${encodeURIComponent(unit)}&limit=100`) }); const compare = useMutation({ mutationFn: () => request<any>('/comparisons', { method: 'POST', body: JSON.stringify({ cost_item_ids: selected }) }) }); const columns = useMemo<ColumnDef<CostItem>[]>(() => [{ header: '编码', accessorKey: 'code' }, { header: '清单项目', cell: c => <div className="item-cell"><strong>{c.row.original.name}</strong><small>{c.row.original.specification || c.row.original.description}</small></div> }, { header: '单位', accessorKey: 'unit' }, { header: '综合单价', cell: c => <b className="money">{formatAmount(c.row.original.unit_price)}</b> }, { header: '项目 / 时间', cell: c => <div>{c.row.original.project_name}<small>{c.row.original.region} · {c.row.original.pricing_date}</small></div> }, { header: '专业', accessorKey: 'specialty' }], []); const table = useReactTable({ data: result.data?.items || [], columns, getCoreRowModel: getCoreRowModel() }), current = result.data?.items.find(i => i.id === active)
  return <section className="page"><Title title="造价数据检索" text="保留原始口径，并可回到 Excel 来源。">{selected.length >= 2 && <Button className="primary" onClick={() => compare.mutate()}><GitCompareArrows />对比 {selected.length} 项</Button>}</Title><div className="searchbar"><Search /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="输入清单名称、编码、项目特征或规格" /><select value={unit} onChange={e => setUnit(e.target.value)}><option value="">全部单位</option><option>m2</option><option>m3</option><option>t</option><option>项</option></select><span>{result.data?.total || 0} 条</span></div><ErrorLine error={result.error || compare.error} />{compare.data && <div className="comparison-strip"><div><span>最低价</span><strong>¥ {formatAmount(compare.data.min_price)}</strong></div><div><span>中位价</span><strong>¥ {formatAmount(compare.data.median_price)}</strong></div><div><span>最高价</span><strong>¥ {formatAmount(compare.data.max_price)}</strong></div><p>{compare.data.warnings?.join('；') || `${compare.data.sample_count} 个样本`}</p><Button onClick={() => compare.reset()}><X /></Button></div>}<div className="explorer-grid"><div className="panel table-panel">{!result.data?.items.length ? <Empty text="没有符合条件的数据" /> : <div className="table-scroll"><table><thead>{table.getHeaderGroups().map(g => <tr key={g.id}><th />{g.headers.map(h => <th key={h.id}>{flexRender(h.column.columnDef.header, h.getContext())}</th>)}</tr>)}</thead><tbody>{table.getRowModel().rows.map(row => <tr key={row.id} className={active === row.original.id ? 'selected' : ''} onClick={() => setActive(row.original.id)}><td><input type="checkbox" checked={selected.includes(row.original.id)} onClick={e => e.stopPropagation()} onChange={e => setSelected(v => e.target.checked ? [...v, row.original.id] : v.filter(id => id !== row.original.id))} /></td>{row.getVisibleCells().map(c => <td key={c.id}>{flexRender(c.column.columnDef.cell, c.getContext())}</td>)}</tr>)}</tbody></table></div>}</div><Evidence item={current} /></div></section>
}
function Evidence({ item }: { item?: CostItem }) { return <aside className="evidence"><div className="panel-head"><div><h2>来源与口径</h2><p>证据先于结论</p></div></div>{!item ? <Empty text="请选择清单项" /> : <div className="evidence-body"><span>原始综合单价</span><div className="big-price">¥ {formatAmount(item.unit_price)} <small>/ {item.unit || '—'}</small></div><dl><dt>编码</dt><dd>{item.code || '—'}</dd><dt>项目</dt><dd>{item.project_name}</dd><dt>计价口径</dt><dd>{item.pricing_mode}</dd><dt>地区 / 时间</dt><dd>{item.region} / {item.pricing_date}</dd></dl><div className="source"><Archive /><div><strong>{item.source.file_name}</strong><span>{item.source.sheet_name} · 第 {item.source.start_row} 行</span></div></div><h3>综合单价组成</h3>{item.components.length ? item.components.map(c => <div className="component" key={c.id}><span>{c.category} · {c.name}</span><b>{formatAmount(c.amount)}</b></div>) : <p className="muted">当前来源未关联组成数据</p>}</div>}</aside> }

function Matching() {
  const [name, setName] = useState(''), [unit, setUnit] = useState('m3'), [saved, setSaved] = useState(''); const create = useMutation({ mutationFn: () => request<any>('/match-sessions', { method: 'POST', body: JSON.stringify({ name: `匹配 ${new Date().toLocaleDateString()}`, items: [{ name, unit }] }) }) }); const decide = useMutation({ mutationFn: (id: string) => request(`/match-sessions/${create.data.id}/decisions`, { method: 'POST', body: JSON.stringify({ query_index: 0, candidate_cost_item_id: id, decision: 'accepted', remember_rule: true }) }), onSuccess: (_d, id) => setSaved(id) })
  return <section className="page"><Title title="新清单匹配" text="确定性召回和评分，显示评分组成与排除原因。" /><div className="panel match-work"><div className="match-input"><label>待匹配清单名称<input value={name} onChange={e => setName(e.target.value)} placeholder="例如：现浇混凝土矩形柱 C30" /></label><label>单位<input value={unit} onChange={e => setUnit(e.target.value)} /></label><Button className="primary" disabled={!name || create.isPending} onClick={() => { setSaved(''); create.mutate() }}>{create.isPending ? <LoaderCircle className="spin" /> : <Search />}查找候选</Button></div><ErrorLine error={create.error || decide.error} />{!create.data ? <Empty text="输入清单项以生成候选" /> : <div className="candidate-list">{create.data.results?.[0]?.candidates?.map((c: any, i: number) => <article key={c.cost_item.id}><div className="rank">{i + 1}</div><div><strong>{c.cost_item.name}</strong><small>{c.cost_item.project_name} · {c.cost_item.region} · {c.cost_item.pricing_date}</small><div className="score-parts">{c.score_parts.map((p: any) => <span key={p.label}>{p.label} {p.score}</span>)}</div></div><div className="candidate-price"><b>¥ {formatAmount(c.cost_item.unit_price)}</b><span>{c.total_score} 分</span></div><Button disabled={!!saved} onClick={() => decide.mutate(c.cost_item.id)}><Check />{saved === c.cost_item.id ? '已确认' : '确认并记住'}</Button></article>)}</div>}</div></section>
}

function Rules() {
  const qc = useQueryClient(), rules = useQuery({ queryKey: ['rules'], queryFn: () => request<Rule[]>('/normalization-rules') }), toggle = useMutation({ mutationFn: (r: Rule) => request(`/normalization-rules/${r.id}`, { method: 'PATCH', body: JSON.stringify({ enabled: !r.enabled }) }), onSuccess: () => qc.invalidateQueries({ queryKey: ['rules'] }) }); return <section className="page"><Title title="标准化规则" text="匹配确认生成的个人规则可以随时停用。" /><div className="panel">{!rules.data?.length ? <Empty text="尚未建立个人规则" /> : <div className="table-scroll"><table><thead><tr><th>类型</th><th>原始值</th><th>标准值</th><th>来源</th><th>启用</th></tr></thead><tbody>{rules.data.map(r => <tr key={r.id}><td>{r.rule_type}</td><td>{r.source_value}</td><td>{r.target_value}</td><td>{r.source}</td><td><input type="checkbox" checked={r.enabled} onChange={() => toggle.mutate(r)} /></td></tr>)}</tbody></table></div>}</div></section>
}

function SystemSettings() {
  const qc = useQueryClient(), backups = useQuery({ queryKey: ['backups'], queryFn: () => request<Backup[]>('/backups') }), ai = useQuery({ queryKey: ['ai'], queryFn: () => request<any>('/settings/ai') }), backup = useMutation({ mutationFn: (dir: string) => request('/backups', { method: 'POST', body: JSON.stringify({ target_directory: dir, kind: 'manual' }) }), onSuccess: () => qc.invalidateQueries({ queryKey: ['backups'] }) }); const submitBackup = (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); backup.mutate(String(new FormData(e.currentTarget).get('directory'))) }; const submitAI = async (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget); await request('/settings/ai', { method: 'PUT', body: JSON.stringify({ base_url: f.get('base_url'), model: f.get('model'), api_key: f.get('api_key') || null }) }); qc.invalidateQueries({ queryKey: ['ai'] }) }
  return <section className="page"><Title title="备份与 AI" text="备份包含数据库和原始文件；密钥仅存 macOS Keychain。" /><div className="settings-grid"><div className="panel"><div className="panel-head"><h2>本地备份</h2></div><form className="settings-form" onSubmit={submitBackup}><label>备份目录<input name="directory" placeholder="/Volumes/Backup/cost-data" required /></label><Button className="primary"><Archive />立即备份</Button></form><ErrorLine error={backup.error} /><div className="backup-list">{backups.data?.map(b => <div key={b.id}><div><strong>{new Date(b.created_at).toLocaleString()}</strong><small>{b.path}</small></div><Status value={b.status} /></div>)}</div></div><div className="panel"><div className="panel-head"><div><h2>DeepSeek</h2><p>关闭时不影响核心功能</p></div><Bot /></div>{ai.data && <form className="settings-form" onSubmit={submitAI}><label>API 地址<input name="base_url" defaultValue={ai.data.base_url} /></label><label>模型<input name="model" defaultValue={ai.data.model} /></label><label>API Key<input name="api_key" type="password" placeholder={ai.data.has_api_key ? '已存入 Keychain' : '尚未配置'} /></label><Button className="primary">保存 AI 设置</Button></form>}</div></div></section>
}

export default App
