import { FormEvent, useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ColumnDef, flexRender, getCoreRowModel, useReactTable } from '@tanstack/react-table'
import { Archive, BarChart3, Bot, Check, ChevronDown, ChevronRight, CircleAlert, Database, FileSearch, FolderKanban, FolderUp, GitCompareArrows, Home, Layers3, LoaderCircle, PackageSearch, Pencil, Plus, RefreshCw, Search, Settings, ShieldCheck, SlidersHorizontal, TriangleAlert, X } from 'lucide-react'
import { Backup, Benchmark, bootstrap, CostItem, formatAmount, ImportIssue, ImportJob, ImportParsePreview, isStaticDemo, LibraryKey, LibrarySummary, MetricTemplate, Project, ProjectDetail, QualityReport, request, Rule, SearchResult, UnitConversion, WorkspaceRecord, WorkspaceSearchResult } from './api'

type View = 'overview' | 'projects' | 'imports' | 'explorer' | 'catalog' | 'resource' | 'quota' | 'quality' | 'matching' | 'rules' | 'settings'
const labels: Record<View, string> = { overview: '总览', projects: '项目库', imports: '项目与导入', explorer: '造价数据工作台（跨库总览）', catalog: '清单库', resource: '工料机库', quota: '定额库', quality: '数据质量中心', matching: '清单匹配', rules: '标准化规则', settings: '备份与 AI' }
const nav = [['overview', Home], ['projects', FolderKanban], ['imports', FolderUp], ['explorer', FileSearch], ['catalog', Layers3], ['resource', PackageSearch], ['quota', Database], ['quality', TriangleAlert], ['matching', GitCompareArrows], ['rules', SlidersHorizontal], ['settings', Settings]] as const
const Button = ({ children, className = '', ...props }: React.ButtonHTMLAttributes<HTMLButtonElement>) => <button className={`button ${className}`} {...props}>{children}</button>
const Status = ({ value }: { value: string }) => <span className={`status status-${value}`}>{({ published: '已发布', review: '待复核', completed: '已完成', analyzing: '结构分析', parsing: '解析中', mapping_review: '待确认映射', running: '解析中', queued: '等待中', draft: '草稿', resolved: '已处理', ignored: '已忽略', open: '待处理', complete: '成功' } as Record<string, string>)[value] || value}</span>
const Empty = ({ text }: { text: string }) => <div className="empty"><Database /><strong>{text}</strong><span>完成首次导入后，这里会显示可核查的数据。</span></div>
const ErrorLine = ({ error }: { error: unknown }) => error ? <div className="error-line">{error instanceof Error ? error.message : '请求失败'}</div> : null
const formatProjectFeature = (value?: string) => {
  if (!value) return '—'
  const formatted = value
    .replace(/^\s*项目特征\s*[:：]\s*/u, '')
    .replace(/\s*工作内容\s*[:：]\s*/gu, '\n工作内容\n')
    .replace(/(?:^|\s)(\d+[.、])\s*/gu, '\n$1 ')
    .replace(/[:：]/gu, '：')
    .replace(/[ \t]+\n/gu, '\n')
    .replace(/\n{2,}/gu, '\n')
    .trim()
  return formatted || '—'
}

export function App() {
  const [view, setView] = useState<View>('overview'); const health = useQuery({ queryKey: ['health'], queryFn: bootstrap })
  return <div className="shell"><aside><div className="brand"><span className="brand-mark">造</span><div><strong>工程造价数据库</strong><small>历史数据资产库</small></div></div><nav aria-label="主导航">{nav.map(([id, Icon]) => <button key={id} className={view === id ? 'active' : ''} onClick={() => setView(id)}><Icon />{labels[id]}</button>)}</nav><div className="local-state"><ShieldCheck /><div><strong>{isStaticDemo ? '在线静态预览' : '数据保存在本机'}</strong><small>{isStaticDemo ? '未连接本地数据服务' : health.isSuccess ? '本地服务运行正常' : '正在连接本地服务'}</small></div></div></aside><main><header><div><span>工程造价数据库</span><ChevronRight /><strong>{labels[view]}</strong></div><span className="preview">{isStaticDemo ? '在线静态演示' : '分库架构'}</span></header>{view === 'overview' && <Overview go={setView} />}{view === 'projects' && <Projects />}{view === 'imports' && <Imports />}{view === 'explorer' && <Explorer go={library => setView(library)} />}{(['catalog', 'resource', 'quota'] as const).includes(view as LibraryKey) && <LibraryExplorer library={view as LibraryKey} ready={health.isSuccess || isStaticDemo} />}{view === 'quality' && <QualityCenter />}{view === 'matching' && <Matching />}{view === 'rules' && <Rules />}{view === 'settings' && <SystemSettings />}</main></div>
}

function Overview({ go }: { go: (v: View) => void }) {
  const stats = useQuery({ queryKey: ['dashboard'], queryFn: () => request<Record<string, number>>('/dashboard') }); const projects = useQuery({ queryKey: ['projects'], queryFn: () => request<Project[]>('/projects') }); const d = stats.data || { projects: 0, published_versions: 0, cost_items: 0, open_issues: 0 }
  return <section className="page"><Title title="数据工作总览" text="先处理异常，再使用已发布数据进行检索与比较。"><Button className="primary" onClick={() => go('imports')}><Plus />导入项目</Button></Title><ErrorLine error={stats.error} /><div className="stats"><div><span>项目</span><strong>{d.projects}</strong></div><div><span>已发布版本</span><strong>{d.published_versions}</strong></div><div><span>可检索清单项</span><strong>{d.cost_items}</strong></div><div className="warn"><span>待处理异常</span><strong>{d.open_issues}</strong></div></div><div className="panel"><div className="panel-head"><div><h2>最近项目</h2><p>发布后才进入正式检索库</p></div></div>{!projects.data?.length ? <Empty text="尚未导入项目" /> : <div className="table-scroll"><table><thead><tr><th>项目</th><th>地区 / 时间</th><th>专业</th><th>计价体系</th><th>清单项</th><th>版本</th></tr></thead><tbody>{projects.data.map(p => <tr key={p.id}><td><strong>{p.name}</strong><small>{p.result_stage}</small></td><td>{p.region}<small>{p.pricing_date}</small></td><td>{p.specialty}</td><td>{p.pricing_mode}</td><td>{p.item_count}</td><td><Status value={p.latest_status || 'draft'} /></td></tr>)}</tbody></table></div>}</div></section>
}

function Title({ title, text, children }: { title: string; text: string; children?: React.ReactNode }) { return <div className="page-title"><div><h1>{title}</h1><p>{text}</p></div>{children}</div> }

function BenchmarkPanel({ code, project }: { code: string; project: ProjectDetail['project'] }) {
  const benchmark = useQuery({ queryKey: ['benchmark', code, project.project_type, project.specialty], queryFn: () => request<Benchmark>(`/benchmarks/metrics/${code}?project_type=${encodeURIComponent(project.project_type || '')}&specialty=${encodeURIComponent(project.specialty)}`) });
  if (!benchmark.data) return null
  return <div className="benchmark"><span>同类项目标杆 · {benchmark.data.sample_count} 个样本</span><div><b>P25 {formatAmount(benchmark.data.p25)}</b><b>P50 {formatAmount(benchmark.data.p50)}</b><b>P75 {formatAmount(benchmark.data.p75)}</b></div></div>
}

function Projects() {
  const qc = useQueryClient(), [selected, setSelected] = useState<string>(); const projects = useQuery({ queryKey: ['projects'], queryFn: () => request<Project[]>('/projects') }); const detail = useQuery({ queryKey: ['project', selected], queryFn: () => request<ProjectDetail>(`/projects/${selected}`), enabled: !!selected }); const saveProfile = useMutation({ mutationFn: (profile: Record<string, string>) => request(`/projects/${selected}/profile`, { method: 'PATCH', body: JSON.stringify({ profile }) }), onSuccess: () => qc.invalidateQueries({ queryKey: ['projects'] }) });
  const submit = (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const form = new FormData(e.currentTarget); saveProfile.mutate(Object.fromEntries(['structure_form', 'area_basis', 'above_ground_area', 'underground_area', 'floors', 'height', 'decoration_grade', 'foundation_type', 'contract_mode', 'tax_rate'].map(key => [key, String(form.get(key) || '')]))) }
  return <section className="page"><Title title="项目库" text="项目画像决定哪些历史样本可以进入同类项目标杆库。" /><div className="split"><div className="panel"><div className="panel-head"><h2>历史项目</h2></div>{!projects.data?.length ? <Empty text="尚未导入项目" /> : <div className="task-list">{projects.data.map(project => <button key={project.id} className={selected === project.id ? 'selected' : ''} onClick={() => setSelected(project.id)}><div><strong>{project.name}</strong><small>{project.region} · {project.pricing_date} · {project.project_type || '未分类'}</small></div><Status value={project.comparability || 'low'} /><b>{project.item_count}</b><ChevronRight /></button>)}</div>}</div><div className="panel review">{!detail.data ? <Empty text="选择项目以查看数据资产" /> : <><div className="panel-head"><div><h2>{detail.data.project.name}</h2><p>{detail.data.project.region} · {detail.data.project.pricing_date} · {detail.data.project.pricing_mode}</p></div><Status value={detail.data.project.comparability} /></div><div className="asset-counts">{Object.entries(detail.data.data_counts).map(([key, count]) => <div key={key}><span>{({ bill: '清单', quota: '定额', resource: '工料机', measure: '措施费', fee_rate: '费率', metric: '指标' } as Record<string, string>)[key]}</span><strong>{count}</strong></div>)}</div><form className="profile-form" onSubmit={submit}><h3>项目画像</h3><label>结构形式<input name="structure_form" defaultValue={detail.data.project.profile.structure_form || ''} placeholder="例如：框架剪力墙" /></label><label>面积口径<input name="area_basis" defaultValue={detail.data.project.profile.area_basis || ''} placeholder="例如：总建筑面积" /></label><label>地上面积<input name="above_ground_area" defaultValue={detail.data.project.profile.above_ground_area || ''} /></label><label>地下面积<input name="underground_area" defaultValue={detail.data.project.profile.underground_area || ''} /></label><label>层数<input name="floors" defaultValue={detail.data.project.profile.floors || ''} /></label><label>装修档次<input name="decoration_grade" defaultValue={detail.data.project.profile.decoration_grade || ''} /></label><label>基础形式<input name="foundation_type" defaultValue={detail.data.project.profile.foundation_type || ''} /></label><label>合同模式<input name="contract_mode" defaultValue={detail.data.project.profile.contract_mode || ''} /></label><label>税率<input name="tax_rate" defaultValue={detail.data.project.profile.tax_rate || ''} /></label><Button className="primary" disabled={saveProfile.isPending}><Check />保存画像</Button></form><div className="metric-list"><h3>项目指标与标杆</h3>{detail.data.metrics.map(metric => <div key={metric.id}><span>{metric.name}<small>{metric.formula}</small></span><b>{formatAmount(metric.value)} {metric.value.unit}</b><BenchmarkPanel code={metric.code} project={detail.data.project} /></div>)}</div></>}</div></div></section>
}

function QualityCenter() {
  const projects = useQuery({ queryKey: ['projects'], queryFn: () => request<Project[]>('/projects') }); const [version, setVersion] = useState<string>(); const report = useQuery({ queryKey: ['quality', version], queryFn: () => request<QualityReport>(`/quality/projects/${version}`), enabled: !!version });
  return <section className="page"><Title title="数据质量中心" text="异常数据可检索但不进入标杆样本池；阻断错误不可发布。" /><div className="panel"><div className="quality-picker"><label>项目版本<select value={version || ''} onChange={event => setVersion(event.target.value)}><option value="">选择已发布版本</option>{projects.data?.filter(project => project.latest_version_id).map(project => <option key={project.latest_version_id} value={project.latest_version_id}>{project.name} · V{project.latest_version_no}</option>)}</select></label></div>{!version ? <Empty text="选择项目版本以生成质量报告" /> : !report.data ? <Empty text="正在计算质量报告" /> : <><div className="quality-stats"><div className="quality-stat good"><span>可发布</span><strong>{report.data.publishable ? '是' : '否'}</strong></div><div className="quality-stat info"><span>待确认</span><strong>{report.data.summary.warnings}</strong></div><div className="quality-stat danger"><span>阻断错误</span><strong>{report.data.summary.errors}</strong></div></div>{!report.data.issues.length ? <Empty text="未发现需要处理的质量问题" /> : <div className="table-scroll"><table><thead><tr><th>级别</th><th>规则</th><th>问题</th><th>来源</th></tr></thead><tbody>{report.data.issues.map((issue, index) => <tr key={`${issue.code}-${index}`}><td><Status value={issue.severity === 'error' ? 'open' : 'review'} /></td><td><code>{issue.code}</code></td><td>{issue.message}</td><td>{issue.source ? `${issue.source.file_name} · ${issue.source.sheet_name} · ${issue.source.start_row} 行` : '项目画像'}</td></tr>)}</tbody></table></div>}</>}</div></section>
}

function Imports() {
  const qc = useQueryClient(), [open, setOpen] = useState(false), [selected, setSelected] = useState<string>()
  const projects = useQuery({ queryKey: ['projects'], queryFn: () => request<Project[]>('/projects') })
  const jobs = useQuery({ queryKey: ['imports'], queryFn: () => request<ImportJob[]>('/imports'), refetchInterval: q => q.state.data?.some(j => ['queued', 'analyzing', 'parsing'].includes(j.status)) ? 1200 : false })
  const selectedJob = jobs.data?.find(job => job.id === selected)
  const issues = useQuery({ queryKey: ['issues', selected], queryFn: () => request<ImportIssue[]>(`/imports/${selected}/issues`), enabled: !!selected })
  const preview = useQuery({ queryKey: ['parse-preview', selected], queryFn: () => request<ImportParsePreview>(`/imports/${selected}/parse-preview`), enabled: selectedJob?.status === 'mapping_review' })
  const resolve = useMutation({ mutationFn: ({ job, issue }: { job: string; issue: string }) => request(`/imports/${job}/issues/${issue}`, { method: 'PATCH', body: JSON.stringify({ status: 'ignored', resolution: '用户确认忽略' }) }), onSuccess: () => { qc.invalidateQueries({ queryKey: ['issues'] }); qc.invalidateQueries({ queryKey: ['imports'] }) } })
  const confirm = useMutation({ mutationFn: (tables: ImportParsePreview['tables']) => request(`/imports/${selected}/confirm-mapping`, { method: 'POST', body: JSON.stringify({ tables, save_profile: true }) }), onSuccess: () => qc.invalidateQueries() })
  const publish = useMutation({ mutationFn: (id: string) => request(`/imports/${id}/publish`, { method: 'POST' }), onSuccess: () => { qc.invalidateQueries(); setSelected(undefined) } })
  return <section className="page"><Title title="项目与导入" text="原始文件按哈希归档，异常复核后事务发布。"><Button className="primary" onClick={() => setOpen(true)}><FolderUp />选择 Excel</Button></Title><ErrorLine error={jobs.error || publish.error || confirm.error} /><div className="split"><div className="panel"><div className="panel-head"><h2>导入任务</h2><Button title="刷新" onClick={() => jobs.refetch()}><RefreshCw /></Button></div>{!jobs.data?.length ? <Empty text="暂无导入任务" /> : <div className="task-list">{jobs.data.map(j => <button key={j.id} className={selected === j.id ? 'selected' : ''} onClick={() => setSelected(j.id)}><div><strong>{projects.data?.find(p => p.id === j.project_id)?.name || '项目'}</strong><small>{new Date(j.created_at).toLocaleString()} · {j.processed_files}/{j.total_files} 文件</small></div><div className="progress"><span style={{ width: `${j.progress}%` }} /></div><Status value={j.status} />{j.open_issue_count > 0 && <b>{j.open_issue_count}</b>}</button>)}</div>}</div><div className="panel review"><div className="panel-head"><div><h2>{selectedJob?.status === 'mapping_review' ? '字段映射确认' : '异常复核'}</h2><p>未识别内容不会静默进入正式数据</p></div>{selectedJob?.status === 'review' && <Button className="primary" onClick={() => publish.mutate(selectedJob.id)}><Check />发布版本</Button>}</div>{!selected ? <Empty text="请选择导入任务" /> : selectedJob?.status === 'mapping_review' ? <MappingReview preview={preview.data} pending={confirm.isPending} onConfirm={tables => confirm.mutate(tables)} /> : !issues.data?.length ? <Empty text="该任务没有异常" /> : <div className="issue-list">{issues.data.map(i => <article key={i.id}><div><Status value={i.status} /><code>{i.code}</code></div><strong>{i.message}</strong><small>{i.sheet_name || '工作簿'} {i.cell_range || ''}</small>{i.status === 'open' && <Button onClick={() => resolve.mutate({ job: selected, issue: i.id })}><X />忽略并记录</Button>}</article>)}</div>}</div></div>{open && <ImportDialog close={() => setOpen(false)} done={() => { setOpen(false); qc.invalidateQueries() }} />}</section>
}

function MappingReview({ preview, pending, onConfirm }: { preview?: ImportParsePreview; pending: boolean; onConfirm: (tables: ImportParsePreview['tables']) => void }) {
  if (!preview) return <Empty text="正在读取工作表结构" />
  return <div className="mapping-review">{preview.tables.map((table, index) => <article key={`${table.source_file_id}-${table.sheet_name}`}><div><strong>{table.sheet_name}</strong><small>{table.report_type} · 表头第 {table.header_rows.join('、')} 行</small></div><table><thead><tr><th>系统字段</th><th>原始表头路径</th></tr></thead><tbody>{Object.entries(table.columns).map(([field, detail]) => <tr key={field}><td><code>{field}</code></td><td>{detail.header_path.join(' / ') || `第 ${detail.column} 列`}</td></tr>)}</tbody></table>{index === preview.tables.length - 1 && <Button className="primary" disabled={pending} onClick={() => onConfirm(preview.tables)}><Check />确认映射并解析</Button>}</article>)}</div>
}
function ImportDialog({ close, done }: { close: () => void; done: () => void }) {
  const [files, setFiles] = useState<FileList | null>(null), [error, setError] = useState(''); const submit = async (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget), body = new FormData(); body.set('metadata_json', JSON.stringify({ name: f.get('name'), region: f.get('region'), pricing_date: f.get('pricing_date'), specialty: f.get('specialty'), pricing_mode: f.get('pricing_mode'), result_stage: f.get('result_stage'), area: f.get('area') || null })); if (files) Array.from(files).forEach(file => body.append('files', file)); try { await request('/imports', { method: 'POST', body }); done() } catch (x) { setError(x instanceof Error ? x.message : '导入失败') } }
  return <div className="modal-backdrop"><form className="modal" onSubmit={submit}><div className="panel-head"><h2>导入项目 Excel</h2><Button type="button" onClick={close}><X /></Button></div><div className="form-grid"><label className="span-2">项目名称<input name="name" required /></label><label>地区<input name="region" defaultValue="西安" required /></label><label>计价时间<input name="pricing_date" type="month" required /></label><label>专业<select name="specialty"><option>土建</option><option>安装</option><option>市政</option><option>装饰</option></select></label><label>计价体系<select name="pricing_mode"><option>内地清单定额</option><option>港式清单</option></select></label><label>成果阶段<select name="result_stage"><option>结算</option><option>预算</option><option>概算</option></select></label><label>建筑面积（m²）<input name="area" /></label><label className="span-2 file-drop">Excel 文件<input type="file" multiple accept=".xlsx,.xlsm" required onChange={e => setFiles(e.target.files)} /><span>支持清单计价、综合单价分析、工料机和措施项目表</span></label></div>{error && <div className="error-line">{error}</div>}<footer><Button type="button" onClick={close}>取消</Button><Button className="primary"><FolderUp />开始导入</Button></footer></form></div>
}

const libraryLabels: Record<LibraryKey, string> = { catalog: '清单库', resource: '工料机库', quota: '定额库' }
const LIBRARY_PAGE_SIZE = 50

function Explorer({ go }: { go: (library: LibraryKey) => void }) {
  const [query, setQuery] = useState(''), [dataType, setDataType] = useState('all'), [unit, setUnit] = useState(''), [region, setRegion] = useState(''), [active, setActive] = useState(''); const result = useQuery({ queryKey: ['workspace', query, dataType, unit, region], queryFn: () => request<WorkspaceSearchResult>(`/workspace/search?query=${encodeURIComponent(query)}&data_type=${dataType}&unit=${encodeURIComponent(unit)}&region=${encodeURIComponent(region)}&limit=100`) }); const current = result.data?.items.find(item => item.id === active);
  return <section className="page"><Title title="造价数据工作台（跨库总览）" text="独立 Tab：统一检索清单库、工料机库和定额库。" /><WorkspaceFilters query={query} setQuery={setQuery} dataType={dataType} setDataType={setDataType} region={region} setRegion={setRegion} unit={unit} setUnit={setUnit} total={result.data?.total || 0} /><ErrorLine error={result.error} /><div className="explorer-grid"><div className="panel table-panel"><LibraryTable items={result.data?.items || []} active={active} select={setActive} onLibrary={go} showLibrary /></div><WorkspaceEvidence item={current} /></div></section>
}

function WorkspaceFilters({ query, setQuery, dataType, setDataType, region, setRegion, unit, setUnit, total, showDataType = true }: { query: string; setQuery: (value: string) => void; dataType: string; setDataType: (value: string) => void; region: string; setRegion: (value: string) => void; unit: string; setUnit: (value: string) => void; total: number; showDataType?: boolean }) {
  return <div className="workspace-filters"><div className="searchbar"><Search /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="名称、编码、规格或项目特征" /><span>{total} 条</span></div>{showDataType && <select value={dataType} onChange={event => setDataType(event.target.value)}><option value="all">全部数据</option><option value="bill">清单</option><option value="quota">定额</option><option value="resource">工料机</option></select>}<input value={region} onChange={event => setRegion(event.target.value)} placeholder="地区" /><input value={unit} onChange={event => setUnit(event.target.value)} placeholder="单位" /></div>
}

function LibraryExplorer({ library, ready }: { library: LibraryKey; ready: boolean }) {
  const qc = useQueryClient(), [query, setQuery] = useState(''), [unit, setUnit] = useState(''), [region, setRegion] = useState(''), [active, setActive] = useState(''), [page, setPage] = useState(1), [editing, setEditing] = useState<WorkspaceRecord>()
  const libraries = useQuery({ queryKey: ['libraries'], queryFn: () => request<LibrarySummary[]>('/libraries'), enabled: ready })
  const result = useQuery({ queryKey: ['library', library, query, unit, region, page], queryFn: () => request<WorkspaceSearchResult>(`/libraries/${library}/search?query=${encodeURIComponent(query)}&unit=${encodeURIComponent(unit)}&region=${encodeURIComponent(region)}&offset=${(page - 1) * LIBRARY_PAGE_SIZE}&limit=${LIBRARY_PAGE_SIZE}`), enabled: ready })
  const current = result.data?.items.find(item => item.id === active)
  const summary = libraries.data?.find(item => item.key === library)
  const resetPage = (update: (value: string) => void) => (value: string) => { update(value); setPage(1); setActive('') }
  return <section className="page library-page"><div className="library-toolbar"><Title title={libraryLabels[library]} text={`${summary?.record_count || 0} 条已发布记录 · ${summary?.project_count || 0} 个项目`} /><WorkspaceFilters query={query} setQuery={resetPage(setQuery)} dataType="all" setDataType={() => undefined} region={region} setRegion={resetPage(setRegion)} unit={unit} setUnit={resetPage(setUnit)} total={result.data?.total || 0} showDataType={false} /><ErrorLine error={libraries.error || result.error} /></div><div className="explorer-grid"><div className="panel table-panel"><LibraryTable items={result.data?.items || []} active={active} select={setActive} standardBillColumns={library === 'catalog'} /><LibraryPagination total={result.data?.total || 0} page={page} setPage={nextPage => { setPage(nextPage); setActive('') }} /></div><WorkspaceEvidence item={current} editable={library === 'catalog'} onEdit={() => current && setEditing(current)} onClose={() => setActive('')} /></div>{editing && <BillEditDialog item={editing} close={() => setEditing(undefined)} done={() => { setEditing(undefined); qc.invalidateQueries({ queryKey: ['library', library] }) }} />}</section>
}

function LibraryPagination({ total, page, setPage }: { total: number; page: number; setPage: (page: number) => void }) {
  const pages = Math.max(1, Math.ceil(total / LIBRARY_PAGE_SIZE)), start = total ? (page - 1) * LIBRARY_PAGE_SIZE + 1 : 0, end = Math.min(page * LIBRARY_PAGE_SIZE, total)
  return <footer className="library-pagination" aria-label="清单分页"><span>显示 {start}–{end}，共 {total} 条</span><div><Button disabled={page === 1} onClick={() => setPage(page - 1)}>上一页</Button><strong>第 {page} / {pages} 页</strong><Button disabled={page === pages} onClick={() => setPage(page + 1)}>下一页</Button></div></footer>
}

function LibraryTable({ items, active, select, onLibrary, showLibrary = false, standardBillColumns = false }: { items: WorkspaceRecord[]; active: string; select: (id: string) => void; onLibrary?: (library: LibraryKey) => void; showLibrary?: boolean; standardBillColumns?: boolean }) {
  if (!items.length) return <Empty text="没有符合条件的数据" />
  if (standardBillColumns) return <div className="table-scroll"><table className="bill-table"><thead><tr><th>清单编码</th><th>清单名称</th><th>项目特征</th><th>计量单位</th><th>工程量</th><th>综合单价</th><th>合价</th><th>项目 / 时间</th><th>样本状态</th></tr></thead><tbody>{items.map(item => <tr key={`bill-${item.id}`} className={active === item.id ? 'selected' : ''} onClick={() => select(item.id)}><td>{item.code || '—'}</td><td><strong>{item.name}</strong>{item.specification && <small>{item.specification}</small>}</td><td className="feature-cell"><div className="feature-summary">{formatProjectFeature(item.description)}</div></td><td>{item.unit || '—'}</td><td className="num">{formatAmount(item.quantity)}</td><td className="num">{formatAmount(item.unit_price)}</td><td className="num">{formatAmount(item.total)}</td><td>{item.project_name}<small>{item.region} · {item.pricing_date}</small></td><td><Status value={item.comparability} /></td></tr>)}</tbody></table></div>
  return <div className="table-scroll"><table><thead><tr>{showLibrary && <th>所属库</th>}<th>类型</th><th>名称 / 规格</th><th>单位</th><th>数量</th><th>单价</th><th>项目 / 时间</th><th>样本状态</th></tr></thead><tbody>{items.map(item => <tr key={`${item.library || item.data_type}-${item.id}`} className={active === item.id ? 'selected' : ''} onClick={() => select(item.id)}>{showLibrary && <td><button className="library-link" onClick={event => { event.stopPropagation(); if (item.library) onLibrary?.(item.library) }}>{item.library ? libraryLabels[item.library] : '中心库'}</button></td>}<td><Status value={item.data_type} /></td><td><strong>{item.name}</strong><small>{item.code || item.specification || '—'}</small></td><td>{item.unit || '—'}</td><td className="num">{formatAmount(item.quantity)}</td><td className="num">{formatAmount(item.unit_price)}</td><td>{item.project_name}<small>{item.region} · {item.pricing_date}</small></td><td><Status value={item.comparability} /></td></tr>)}</tbody></table></div>
}
function WorkspaceEvidence({ item, editable = false, onEdit, onClose }: { item?: WorkspaceRecord; editable?: boolean; onEdit?: () => void; onClose?: () => void }) {
  const panelHead = <div className="panel-head"><div><h2>证据与口径</h2><p>原始值、标准口径和来源分开呈现</p></div><div className="evidence-actions">{editable && item && <Button onClick={onEdit}><Pencil />编辑清单</Button>}{item && <Button className="icon-button" title="关闭证据面板" aria-label="关闭证据面板" onClick={onClose}><X /></Button>}</div></div>
  if (!item) return <aside className="evidence">{panelHead}<Empty text="选择一条记录查看来源" /></aside>
  const attributes = item.attributes || {}, value = (key: string) => attributes[key] === undefined || attributes[key] === null || attributes[key] === '' ? '—' : typeof attributes[key] === 'string' ? attributes[key] : JSON.stringify(attributes[key])
  const priceContext = item.price_context || {}, hasCompletePrice = !!(priceContext.tax_inclusion && priceContext.price_type && priceContext.price_source)
  const sourceName = item.source?.file_name || value('source')
  const Disclosure = ({ title, children }: { title: string; children: React.ReactNode }) => <details className="evidence-disclosure" open><summary><strong>{title}</strong><ChevronDown /></summary>{children}</details>
  return <aside className="evidence">{panelHead}<div className="evidence-body evidence-reference"><section className="evidence-card price-availability"><h3>价格可用性</h3><div className={`price-alert ${hasCompletePrice ? 'ready' : ''}`}><CircleAlert /><div><strong>{hasCompletePrice ? '价格口径完整' : '价格待确认'}</strong><span>{hasCompletePrice ? '价格来源与口径已完整记录，可用于参考。' : '缺少价格来源数据，仅展示原始值'}</span></div></div><div className="price-metrics"><div><span>价格类型</span><b>{priceContext.price_type || '综合单价'}</b></div><div><span>含税方式</span><b>{priceContext.tax_inclusion || '不含税'}</b></div><div><span>来源状态</span><b>{priceContext.price_source || '待确认'}</b></div><div><span>口径一致性</span><b>{hasCompletePrice ? '一致' : '—'}</b></div></div></section><section className="evidence-card availability-conclusion"><h3>可用性结论</h3><p>{hasCompletePrice ? '当前条目价格口径完整，可作为同类清单的参考样本。' : '当前条目缺少有效价格数据，暂不建议采用。'}</p><p className="suggestion">建议：{hasCompletePrice ? '结合项目时间、地区与适用范围进行比对。' : '补充价格来源或参考同类项目口径后再评估。'}</p>{!hasCompletePrice && editable && <Button onClick={onEdit}>补充价格来源</Button>}</section><section className="evidence-card source-trace"><h3>来源追溯</h3><dl><dt>文件</dt><dd>{sourceName}</dd><dt>工作表</dt><dd>{item.source?.sheet_name || '—'}</dd><dt>行号</dt><dd>第 {item.source?.start_row || '—'} 行</dd><dt>更新时间</dt><dd>—</dd><dt>来源项目</dt><dd>{item.project_name} · {item.region} · {item.pricing_date}</dd></dl></section><Disclosure title="关联定额编码"><p>{value('related_quota_codes')}</p></Disclosure><Disclosure title="适用范围"><p>专业：{value('specialty')}</p><p>适用范围：{value('applicable_scope')}</p></Disclosure><Disclosure title="结构分组"><p>{value('structure_group')}</p></Disclosure><Disclosure title="备注"><p>{value('remark')}</p></Disclosure></div></aside>
}

function BillEditDialog({ item, close, done }: { item: WorkspaceRecord; close: () => void; done: () => void }) {
  const save = useMutation({ mutationFn: (body: Record<string, string | null>) => request<WorkspaceRecord>(`/libraries/catalog/records/${item.id}`, { method: 'PATCH', body: JSON.stringify(body) }), onSuccess: done })
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const value = (key: string) => String(form.get(key) || '').trim() || null; save.mutate({ code: value('code'), name: value('name'), specification: value('specification'), description: value('description'), unit: value('unit'), quantity: value('quantity'), unit_price: value('unit_price'), total: value('total') }) }
  return <div className="modal-backdrop"><form className="modal bill-edit-modal" onSubmit={submit}><div className="panel-head"><div><h2>编辑清单</h2><p>保存后将同步更新清单库；原始文件证据保持不变。</p></div><Button type="button" onClick={close}><X /></Button></div><div className="form-grid"><label>清单编码<input name="code" defaultValue={item.code || ''} /></label><label>计量单位<input name="unit" defaultValue={item.unit || ''} /></label><label className="span-2">清单名称<input name="name" required defaultValue={item.name} /></label><label className="span-2">规格型号<input name="specification" defaultValue={item.specification || ''} /></label><label className="span-2">项目特征<textarea name="description" defaultValue={item.description || ''} /></label><label>工程量<input name="quantity" inputMode="decimal" defaultValue={item.quantity.value || ''} /></label><label>综合单价<input name="unit_price" inputMode="decimal" defaultValue={item.unit_price.value || ''} /></label><label>合价<input name="total" inputMode="decimal" defaultValue={item.total.value || ''} /></label></div><ErrorLine error={save.error} /><footer><Button type="button" onClick={close}>取消</Button><Button className="primary" disabled={save.isPending}><Check />{save.isPending ? '保存中' : '保存修改'}</Button></footer></form></div>
}

function Matching() {
  const [name, setName] = useState(''), [unit, setUnit] = useState('m3'), [saved, setSaved] = useState(''); const create = useMutation({ mutationFn: () => request<any>('/match-sessions', { method: 'POST', body: JSON.stringify({ name: `匹配 ${new Date().toLocaleDateString()}`, items: [{ name, unit }] }) }) }); const decide = useMutation({ mutationFn: (id: string) => request(`/match-sessions/${create.data.id}/decisions`, { method: 'POST', body: JSON.stringify({ query_index: 0, candidate_cost_item_id: id, decision: 'accepted', remember_rule: true }) }), onSuccess: (_d, id) => setSaved(id) })
  return <section className="page"><Title title="新清单匹配" text="确定性召回和评分，显示评分组成与排除原因。" /><div className="panel match-work"><div className="match-input"><label>待匹配清单名称<input value={name} onChange={e => setName(e.target.value)} placeholder="例如：现浇混凝土矩形柱 C30" /></label><label>单位<input value={unit} onChange={e => setUnit(e.target.value)} /></label><Button className="primary" disabled={!name || create.isPending} onClick={() => { setSaved(''); create.mutate() }}>{create.isPending ? <LoaderCircle className="spin" /> : <Search />}查找候选</Button></div><ErrorLine error={create.error || decide.error} />{!create.data ? <Empty text="输入清单项以生成候选" /> : <div className="candidate-list">{create.data.results?.[0]?.candidates?.map((c: any, i: number) => <article key={c.cost_item.id}><div className="rank">{i + 1}</div><div><strong>{c.cost_item.name}</strong><small>{c.cost_item.project_name} · {c.cost_item.region} · {c.cost_item.pricing_date}</small><div className="score-parts">{c.score_parts.map((p: any) => <span key={p.label}>{p.label} {p.score}</span>)}</div></div><div className="candidate-price"><b>¥ {formatAmount(c.cost_item.unit_price)}</b><span>{c.total_score} 分</span></div><Button disabled={!!saved} onClick={() => decide.mutate(c.cost_item.id)}><Check />{saved === c.cost_item.id ? '已确认' : '确认并记住'}</Button></article>)}</div>}</div></section>
}

function Rules() {
  const qc = useQueryClient(), rules = useQuery({ queryKey: ['rules'], queryFn: () => request<Rule[]>('/normalization-rules') }), conversions = useQuery({ queryKey: ['conversions'], queryFn: () => request<UnitConversion[]>('/unit-conversions') }), templates = useQuery({ queryKey: ['templates'], queryFn: () => request<MetricTemplate[]>('/metric-templates') }); const toggle = useMutation({ mutationFn: (r: Rule) => request(`/normalization-rules/${r.id}`, { method: 'PATCH', body: JSON.stringify({ enabled: !r.enabled }) }), onSuccess: () => qc.invalidateQueries({ queryKey: ['rules'] }) }); const createConversion = useMutation({ mutationFn: (body: Record<string, string>) => request('/unit-conversions', { method: 'POST', body: JSON.stringify(body) }), onSuccess: () => qc.invalidateQueries({ queryKey: ['conversions'] }) }); const createTemplate = useMutation({ mutationFn: (body: Record<string, string>) => request('/metric-templates', { method: 'POST', body: JSON.stringify(body) }), onSuccess: () => qc.invalidateQueries({ queryKey: ['templates'] }) });
  return <section className="page"><Title title="标准化与主数据" text="原始值不被覆盖；标准名称、单位换算和指标模板均可追溯。" /><div className="settings-grid"><div className="panel"><div className="panel-head"><h2>名称与分类规则</h2></div>{!rules.data?.length ? <Empty text="尚未建立个人规则" /> : <div className="table-scroll"><table><thead><tr><th>类型</th><th>原始值</th><th>标准值</th><th>启用</th></tr></thead><tbody>{rules.data.map(r => <tr key={r.id}><td>{r.rule_type}</td><td>{r.source_value}</td><td>{r.target_value}</td><td><input type="checkbox" checked={r.enabled} onChange={() => toggle.mutate(r)} /></td></tr>)}</tbody></table></div>}</div><div className="panel"><div className="panel-head"><h2>单位换算</h2></div><form className="settings-form" onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); createConversion.mutate(Object.fromEntries(['source_unit', 'target_unit', 'factor', 'basis'].map(key => [key, String(form.get(key))]))) }}><label>原始单位<input name="source_unit" placeholder="t" required /></label><label>标准单位<input name="target_unit" placeholder="kg" required /></label><label>换算系数<input name="factor" placeholder="1000" required /></label><label>换算依据<input name="basis" placeholder="计量换算规则" required /></label><Button className="primary"><Plus />新增换算</Button></form><div className="compact-list">{conversions.data?.map(rule => <div key={rule.id}><span>{rule.source_unit} → {rule.target_unit} × {rule.factor}</span><small>{rule.basis}</small></div>)}</div></div><div className="panel"><div className="panel-head"><h2>指标模板</h2></div><form className="settings-form" onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); createTemplate.mutate(Object.fromEntries(['code', 'name', 'unit', 'formula', 'description'].map(key => [key, String(form.get(key) || '')]))) }}><label>指标编码<input name="code" required /></label><label>指标名称<input name="name" required /></label><label>单位<input name="unit" required /></label><label>计算口径<input name="formula" required /></label><Button className="primary"><Plus />新增模板</Button></form><div className="compact-list">{templates.data?.map(template => <div key={template.id}><span>{template.name} · {template.unit}</span><small>{template.formula}</small></div>)}</div></div></div></section>
}

function SystemSettings() {
  const qc = useQueryClient(), backups = useQuery({ queryKey: ['backups'], queryFn: () => request<Backup[]>('/backups') }), ai = useQuery({ queryKey: ['ai'], queryFn: () => request<any>('/settings/ai') }), backup = useMutation({ mutationFn: (dir: string) => request('/backups', { method: 'POST', body: JSON.stringify({ target_directory: dir, kind: 'manual' }) }), onSuccess: () => qc.invalidateQueries({ queryKey: ['backups'] }) }); const submitBackup = (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); backup.mutate(String(new FormData(e.currentTarget).get('directory'))) }; const submitAI = async (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget); await request('/settings/ai', { method: 'PUT', body: JSON.stringify({ base_url: f.get('base_url'), model: f.get('model'), api_key: f.get('api_key') || null }) }); qc.invalidateQueries({ queryKey: ['ai'] }) }
  return <section className="page"><Title title="备份与 AI" text="备份包含数据库和原始文件；密钥仅存 macOS Keychain。" /><div className="settings-grid"><div className="panel"><div className="panel-head"><h2>本地备份</h2></div><form className="settings-form" onSubmit={submitBackup}><label>备份目录<input name="directory" placeholder="/Volumes/Backup/cost-data" required /></label><Button className="primary"><Archive />立即备份</Button></form><ErrorLine error={backup.error} /><div className="backup-list">{backups.data?.map(b => <div key={b.id}><div><strong>{new Date(b.created_at).toLocaleString()}</strong><small>{b.path}</small></div><Status value={b.status} /></div>)}</div></div><div className="panel"><div className="panel-head"><div><h2>DeepSeek</h2><p>关闭时不影响核心功能</p></div><Bot /></div>{ai.data && <form className="settings-form" onSubmit={submitAI}><label>API 地址<input name="base_url" defaultValue={ai.data.base_url} /></label><label>模型<input name="model" defaultValue={ai.data.model} /></label><label>API Key<input name="api_key" type="password" placeholder={ai.data.has_api_key ? '已存入 Keychain' : '尚未配置'} /></label><Button className="primary">保存 AI 设置</Button></form>}</div></div></section>
}

export default App
