"""initial schema

Revision ID: bd9d97625f1a
Revises: 
Create Date: 2026-07-25 21:43:10.667017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd9d97625f1a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_calls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('capability', sa.String(length=80), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('prompt_version', sa.String(length=40), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=False),
    sa.Column('response_payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_calls_capability'), ['capability'], unique=False)

    op.create_table('ai_consents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('capability', sa.String(length=80), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('remember', sa.Boolean(), nullable=False),
    sa.Column('field_names', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('capability')
    )
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_event_type'), ['event_type'], unique=False)

    op.create_table('match_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('query_items', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('normalization_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rule_type', sa.String(length=40), nullable=False),
    sa.Column('source_value', sa.String(length=500), nullable=False),
    sa.Column('target_value', sa.String(length=500), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('normalization_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_normalization_rules_rule_type'), ['rule_type'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('region', sa.String(length=120), nullable=False),
    sa.Column('pricing_date', sa.String(length=32), nullable=False),
    sa.Column('specialty', sa.String(length=120), nullable=False),
    sa.Column('pricing_mode', sa.String(length=120), nullable=False),
    sa.Column('quota_version', sa.String(length=120), nullable=True),
    sa.Column('result_stage', sa.String(length=120), nullable=False),
    sa.Column('project_type', sa.String(length=120), nullable=True),
    sa.Column('construction_nature', sa.String(length=120), nullable=True),
    sa.Column('area_value', sa.BigInteger(), nullable=True),
    sa.Column('area_scale', sa.Integer(), nullable=False),
    sa.Column('area_unit', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_name'), ['name'], unique=False)

    op.create_table('project_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_versions', schema=None) as batch_op:
        batch_op.create_index('ix_project_version_project_no', ['project_id', 'version_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_project_versions_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_versions_status'), ['status'], unique=False)

    op.create_table('import_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('project_version_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('total_files', sa.Integer(), nullable=False),
    sa.Column('processed_files', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_version_id'], ['project_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_jobs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_jobs_project_version_id'), ['project_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_jobs_status'), ['status'], unique=False)

    op.create_table('project_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_version_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('value', sa.BigInteger(), nullable=True),
    sa.Column('scale', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('formula', sa.Text(), nullable=False),
    sa.Column('numerator_source', sa.JSON(), nullable=False),
    sa.Column('denominator_source', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_version_id'], ['project_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_metrics', schema=None) as batch_op:
        batch_op.create_index('ix_metric_version_code', ['project_version_id', 'code'], unique=True)
        batch_op.create_index(batch_op.f('ix_project_metrics_project_version_id'), ['project_version_id'], unique=False)

    op.create_table('source_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_version_id', sa.String(length=36), nullable=False),
    sa.Column('import_job_id', sa.String(length=36), nullable=False),
    sa.Column('original_name', sa.String(length=500), nullable=False),
    sa.Column('relative_path', sa.String(length=700), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('report_type', sa.String(length=80), nullable=False),
    sa.Column('sheet_names', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_version_id'], ['project_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_files', schema=None) as batch_op:
        batch_op.create_index('ix_source_file_version_hash', ['project_version_id', 'sha256'], unique=True)
        batch_op.create_index(batch_op.f('ix_source_files_import_job_id'), ['import_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_files_project_version_id'), ['project_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_files_sha256'), ['sha256'], unique=False)

    op.create_table('cost_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_version_id', sa.String(length=36), nullable=False),
    sa.Column('source_file_id', sa.String(length=36), nullable=False),
    sa.Column('item_type', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('normalized_name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('specification', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('quantity_value', sa.BigInteger(), nullable=True),
    sa.Column('quantity_scale', sa.Integer(), nullable=False),
    sa.Column('unit_price_value', sa.BigInteger(), nullable=True),
    sa.Column('unit_price_scale', sa.Integer(), nullable=False),
    sa.Column('total_value', sa.BigInteger(), nullable=True),
    sa.Column('total_scale', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=12), nullable=False),
    sa.Column('sheet_name', sa.String(length=240), nullable=False),
    sa.Column('source_row', sa.Integer(), nullable=False),
    sa.Column('source_end_row', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_version_id'], ['project_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cost_items', schema=None) as batch_op:
        batch_op.create_index('ix_cost_item_search', ['project_version_id', 'code', 'name'], unique=False)
        batch_op.create_index('ix_cost_item_source_row', ['source_file_id', 'sheet_name', 'source_row'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_items_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_items_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_items_project_version_id'), ['project_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_items_source_file_id'), ['source_file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_items_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_items_unit'), ['unit'], unique=False)

    op.create_table('fee_rates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_version_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('rate_value', sa.BigInteger(), nullable=True),
    sa.Column('rate_scale', sa.Integer(), nullable=False),
    sa.Column('basis', sa.String(length=500), nullable=True),
    sa.Column('source_file_id', sa.String(length=36), nullable=False),
    sa.Column('sheet_name', sa.String(length=240), nullable=False),
    sa.Column('source_row', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_version_id'], ['project_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fee_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fee_rates_project_version_id'), ['project_version_id'], unique=False)

    op.create_table('import_issues',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('import_job_id', sa.String(length=36), nullable=False),
    sa.Column('source_file_id', sa.String(length=36), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('sheet_name', sa.String(length=240), nullable=True),
    sa.Column('cell_range', sa.String(length=80), nullable=True),
    sa.Column('suggested_action', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_issues_import_job_id'), ['import_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_issues_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_issues_status'), ['status'], unique=False)

    op.create_table('measure_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_version_id', sa.String(length=36), nullable=False),
    sa.Column('source_file_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('amount_value', sa.BigInteger(), nullable=True),
    sa.Column('amount_scale', sa.Integer(), nullable=False),
    sa.Column('sheet_name', sa.String(length=240), nullable=False),
    sa.Column('source_row', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_version_id'], ['project_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('measure_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_measure_items_project_version_id'), ['project_version_id'], unique=False)

    op.create_table('resource_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_version_id', sa.String(length=36), nullable=False),
    sa.Column('source_file_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('specification', sa.String(length=500), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('quantity_value', sa.BigInteger(), nullable=True),
    sa.Column('quantity_scale', sa.Integer(), nullable=False),
    sa.Column('price_value', sa.BigInteger(), nullable=True),
    sa.Column('price_scale', sa.Integer(), nullable=False),
    sa.Column('amount_value', sa.BigInteger(), nullable=True),
    sa.Column('amount_scale', sa.Integer(), nullable=False),
    sa.Column('sheet_name', sa.String(length=240), nullable=False),
    sa.Column('source_row', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_version_id'], ['project_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resource_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resource_items_project_version_id'), ['project_version_id'], unique=False)
        batch_op.create_index('ix_resource_project_name', ['project_version_id', 'name'], unique=False)

    op.create_table('match_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('match_session_id', sa.String(length=36), nullable=False),
    sa.Column('query_index', sa.Integer(), nullable=False),
    sa.Column('candidate_cost_item_id', sa.String(length=36), nullable=True),
    sa.Column('decision', sa.String(length=24), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_cost_item_id'], ['cost_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['match_session_id'], ['match_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_decisions_match_session_id'), ['match_session_id'], unique=False)

    op.create_table('quota_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cost_item_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('consumption_value', sa.BigInteger(), nullable=True),
    sa.Column('consumption_scale', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.String(length=36), nullable=False),
    sa.Column('sheet_name', sa.String(length=240), nullable=False),
    sa.Column('source_row', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cost_item_id'], ['cost_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quota_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quota_items_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_quota_items_cost_item_id'), ['cost_item_id'], unique=False)

    op.create_table('rate_components',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cost_item_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('value', sa.BigInteger(), nullable=True),
    sa.Column('scale', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.String(length=36), nullable=False),
    sa.Column('sheet_name', sa.String(length=240), nullable=False),
    sa.Column('source_row', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cost_item_id'], ['cost_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rate_components', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rate_components_cost_item_id'), ['cost_item_id'], unique=False)

    op.execute(
        "CREATE VIRTUAL TABLE cost_item_fts USING fts5("
        "cost_item_id UNINDEXED, code, name, description, specification, tokenize='trigram')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS cost_item_fts")
    with op.batch_alter_table('rate_components', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rate_components_cost_item_id'))

    op.drop_table('rate_components')
    with op.batch_alter_table('quota_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quota_items_cost_item_id'))
        batch_op.drop_index(batch_op.f('ix_quota_items_code'))

    op.drop_table('quota_items')
    with op.batch_alter_table('match_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_decisions_match_session_id'))

    op.drop_table('match_decisions')
    with op.batch_alter_table('resource_items', schema=None) as batch_op:
        batch_op.drop_index('ix_resource_project_name')
        batch_op.drop_index(batch_op.f('ix_resource_items_project_version_id'))

    op.drop_table('resource_items')
    with op.batch_alter_table('measure_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_measure_items_project_version_id'))

    op.drop_table('measure_items')
    with op.batch_alter_table('import_issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_issues_status'))
        batch_op.drop_index(batch_op.f('ix_import_issues_severity'))
        batch_op.drop_index(batch_op.f('ix_import_issues_import_job_id'))

    op.drop_table('import_issues')
    with op.batch_alter_table('fee_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fee_rates_project_version_id'))

    op.drop_table('fee_rates')
    with op.batch_alter_table('cost_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cost_items_unit'))
        batch_op.drop_index(batch_op.f('ix_cost_items_status'))
        batch_op.drop_index(batch_op.f('ix_cost_items_source_file_id'))
        batch_op.drop_index(batch_op.f('ix_cost_items_project_version_id'))
        batch_op.drop_index(batch_op.f('ix_cost_items_name'))
        batch_op.drop_index(batch_op.f('ix_cost_items_code'))
        batch_op.drop_index('ix_cost_item_source_row')
        batch_op.drop_index('ix_cost_item_search')

    op.drop_table('cost_items')
    with op.batch_alter_table('source_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_files_sha256'))
        batch_op.drop_index(batch_op.f('ix_source_files_project_version_id'))
        batch_op.drop_index(batch_op.f('ix_source_files_import_job_id'))
        batch_op.drop_index('ix_source_file_version_hash')

    op.drop_table('source_files')
    with op.batch_alter_table('project_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_metrics_project_version_id'))
        batch_op.drop_index('ix_metric_version_code')

    op.drop_table('project_metrics')
    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_import_jobs_project_version_id'))
        batch_op.drop_index(batch_op.f('ix_import_jobs_project_id'))

    op.drop_table('import_jobs')
    with op.batch_alter_table('project_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_versions_status'))
        batch_op.drop_index(batch_op.f('ix_project_versions_project_id'))
        batch_op.drop_index('ix_project_version_project_no')

    op.drop_table('project_versions')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_name'))

    op.drop_table('projects')
    with op.batch_alter_table('normalization_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_normalization_rules_rule_type'))

    op.drop_table('normalization_rules')
    op.drop_table('match_sessions')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_event_type'))

    op.drop_table('audit_events')
    op.drop_table('app_settings')
    op.drop_table('ai_consents')
    with op.batch_alter_table('ai_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_calls_capability'))

    op.drop_table('ai_calls')
    # ### end Alembic commands ###
